version: "3.3"

services:
  api:
    image: andreloff/docker-cohome-si
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    environment: 
      MONGO_HOST: db
      MONGO_PORT: 27017

  db:
    image: "mongo"
    ports:
      - 27017:27017